default: &default
  adapter: postgresql
  encoding: utf8
  database: learn
  pool: 5
  host: localhost

development:
  <<: *default
  database: learn_dev

test:
  <<: *default
  database: learn_test

production:
  <<: *default
  database: learn_prod
